[package]
name = "RustyKeys"
version = "0.1.0"
edition = "2021"

[dependencies]
winapi = { version = "0.3", features = [
    "winuser", 
    "processthreadsapi", 
    "psapi", 
    "handleapi", 
    "minwindef"
] }
uuid = { version = "1.2", features = ["v4"] }
